### ISSUE TITLE
FE: CasperLabs Block Explorer Enhancements

### ISSUE THREAD

**Issue by devendran-m** [CasperLabs/product_to_public#5]
This epic will capture block explorer enhancements including and enabled by integrating with the sidecar rather than the node itself.  It is the next evolution of the explorer. It will include:

- [ ] Integrating with the sidecar
- [ ] Updating CI/CD to support continuous delivery
- [ ] Implementing additional environment variables to support configurations
- [ ] UI and implementation of a filtering capability
- [ ] Incorporation of CNM functionality

**Comment by RitaMAllenCA** [comment]
closing this because these enhancements are already captured in the destination repo
